### ISSUE TITLE
Convert file.rpt to file.repx

### ISSUE THREAD

**Issue by TahaAndolsi2501** [DevExpress/Reporting.Import#14]
I want to convert a CrystalReport1.rpt to  CrystalReport1.repx
so i run this command: ReportsImport  /in:e:\CrystalReport1.rpt
/out:e:\converted\CrystalReport1.repx /crystal:UnrecognizedFunctionBehavior=Ignore

 i get this exception : "An exception was thrown by the type initializer for 'CrystalDecisions.CrystalReports.Engine.ReportDocument'."
![image](https://user-images.githubusercontent.com/79594096/109033749-439f1280-76c7-11eb-9da9-437f9e43387b.png)

Thank you

**Comment by k0st1x** [comment]
you can view the real exception in the exception.InnerException under the debugger. or you can run this tool under the debugger with all checked "Common Language runtime Exceptions" like in the [article](https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019#BKMK_UserUnhandled).

**Comment by TahaAndolsi2501** [comment]
thank you but i try for the 2 solutions but still the same Exception

**Comment by TahaAndolsi2501** [comment]
@k0st1x  the problem that i give the CrystalReport1.rpt in the /in and still not read this report and it display  {string[0]}

**Comment by k0st1x** [comment]
check that you have installed https://www.sap.com/cmp/td/sap-crystal-reports-visual-studio-trial.html and it version is 13 or higher.
try to import single rpt file using the [Visual Studio Report Designer Import functionality](https://docs.devexpress.com/XtraReports/1468/get-started-with-devexpress-reporting/convert-third-party-reports-to-devexpress-reports#visual-studio-report-designer).

also you can send here single rpt file so I'll try to reproduce exception.

**Comment by TahaAndolsi2501** [comment]
i did what you said exactly but the method'printReportWithDialog' of type'CrystalDescisons.CrystalReports.Engine.FormatEngine'with assembly 'CrystalDescisons.CrystalReports.Engine.FormatEngine, Version=13.0.2000.0', Culture=neutral,PublickeyToken=       ' has no implementation

![image](https://user-images.githubusercontent.com/79594096/109163855-1495a900-777a-11eb-85a3-5b78778798c0.png)

![image](https://user-images.githubusercontent.com/79594096/109163974-31ca7780-777a-11eb-9338-f5244b6aba9b.png)

**Comment by k0st1x** [comment]
currently i've installed the same version
![image](https://user-images.githubusercontent.com/1209649/109168228-a65be100-778f-11eb-8da8-72be8dd6f507.png)
and tested on simple test rpt layout - no errors.
you can share rpt layout here or in the [support center](https://supportcenter.devexpress.com/)
also provide us the full exception description with stacktrace.
and please test the import feature in the visual studio devexpress report designer as described in the [documentation](https://docs.devexpress.com/XtraReports/1468/get-started-with-devexpress-reporting/convert-third-party-reports-to-devexpress-reports#visual-studio-report-designer).

**Comment by TahaAndolsi2501** [comment]
@k0st1x  hello still not worked please i need a help
![image](https://user-images.githubusercontent.com/79594096/109274827-380d3200-7814-11eb-8567-7b4790d1f827.png)

**Comment by k0st1x** [comment]
I can't see any error on your screenshot.
so expect that you have output repx file.
please be aware that you have warnings so datasource should be generated manually.
also UnrecognizedFunctionsBehavior=Ignore key will convert all functions even unsupported by DevExpress Reporting and should be supported manually in code using the [CustomFunctions](https://docs.devexpress.com/XtraReports/DevExpress.XtraReports.Expressions.CustomFunctions).
