### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by SkyscraperFarms** [DevExpress/Reporting.Import#16]
When I run it in debugging in VS2019 it opens and then immediately quits.

Command line gives this message "File extension '.rpt' is not supported"

**Comment by k0st1x** [comment]
Hello!
In the visual studio you may build project in "Release" configuration where all supported third-party-vendors are included.
Also you may select some "Debug_*" configuration, for example "Debug_Crystal" where SAP Crystal Reports will be supported.
Please try such project configuration and see the result.
Additionally you may read the [Convert Third-Party Reports to DevExpress Reports](https://docs.devexpress.com/XtraReports/1468/get-started-with-devexpress-reporting/convert-third-party-reports-to-devexpress-reports) article for more information.
