### ISSUE TITLE
Compiling the source code

### ISSUE THREAD

**Issue by wakasupi** [DevExpress/Reporting.Import#18]
Hi,
  What are the dependencies to compile this project? I am running VS 2019 and have downloaded and install the Dev Express Universal trial (full install). I see Yellow warrning signs on each external reference. Is there a path or reference that is needed to compile this project locally?

**Comment by k0st1x** [comment]
Hello @wakasupi.
Before compiling the sourcecode, it is neccessary to convert project using DX Project Converter tool https://docs.devexpress.com/ProjectConverter/2529/project-converter . That will convert project references to your specific DX version.
Let me know of any questions.
