### ISSUE TITLE
Convert from rdlc

### ISSUE THREAD

**Issue by jbzcooper** [DevExpress/Reporting.Import#2]
Hi, your website makes reference to converting RDLC files but it does not appear to be so... `*.rdlc` is not in the Import Report supported file type drop down.

> Convert Third-Party Reports
>
>Convert Microsoft Access reports, Crystal Reports, RDLC (SQL Server Reporting Services) reports, and Active Reports to DevExpress Reports within the Visual Sudio Report Designer or use our command-line utility.

Am I correct in assuming your website is mistaken?

**Comment by Yaroslav-Kuznetsov** [comment]
@jbzcooper,
The RDLC support is a feature of the upcoming v20.2 release: https://community.devexpress.com/blogs/reporting/archive/2020/08/24/reporting-early-access-preview-v20-2.aspx
This version is not yet here so the conversion tool doesn't work (the release is scheduled for the end of 2020). If you'd like to participate in beta testing and/or willing to share a few RDLC reports to try, feel free to reach out directly to our product team. For this, raise a question in our Support Center at devexpress.com/ask.

**Comment by jbzcooper** [comment]
This is great news! We are evaluating DevExpress and one of the biggest hurdles is converting hundreds of reports from RDL/RDLC format. This helps seal the deal! ;)
