### ISSUE TITLE
SSRS: Multiple TextRuns

### ISSUE THREAD

**Issue by markgould** [DevExpress/Reporting.Import#4]
First off, this is a great project. We have a lot of SSRS and Crystal Reports we are looking to migrate. We use both DevExpress and some other vendor controls, and nobody has a robust a converter as this. 

Looking at the code, anytime there are multiple TextRuns it combines it into RichText. In most of our cases, multiple text runs are for when there are multiple fields, all the styling is the same.

For example:
```xml
<Paragraphs>
   <Paragraph>
      <TextRuns>
         <TextRun>
            <Value>=Fields!Address1.Value</Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value xml:space="preserve"> </Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value>=Fields!Address2.Value</Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value xml:space="preserve"> </Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value>=Fields!City.Value</Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value>,</Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value>=Fields!State.Value</Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value xml:space="preserve"> </Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
         <TextRun>
            <Value>=Fields!PostalCode.Value</Value>
            <Style>
               <FontSize>7pt</FontSize>
            </Style>
         </TextRun>
      </TextRuns>
      <Style />
   </Paragraph>
</Paragraphs>
```

Could be converted to a single expression, something like: 
`[Address1] [Address2] [City] [State] [PostalCode]`

I started to look at adding an option to the converter to handle this. Are you accepting pull requests on this or would this be something you'd be able to implement?

**Comment by markgould** [comment]
I've got this working now in my local branch. I've also fixed a few other minor issues. I can create a PR for each or just do one big one later this week as I find things. Whichever you'd prefer.

https://github.com/markgould/Reporting.Import/tree/dev

**Comment by k0st1x** [comment]
thank you, markgould. multiple PRs with description is better than a big one.

i think for your current scenario (simple expressions with just a binding without logic) it is better to convert into [embedded fields](https://docs.devexpress.com/XtraReports/2433/detailed-guide-to-devexpress-reporting/use-report-controls/bind-report-controls-to-data/use-embedded-fields-mail-merge) instead of expressionbinding usage.
