### ISSUE TITLE
SSRS: Group footer levels

### ISSUE THREAD

**Issue by markgould** [DevExpress/Reporting.Import#6]
There is an issue with group footers, if not all groups have footers.

Here's a screenshot from SSRS: 
![image](https://user-images.githubusercontent.com/2712328/104106225-de5ba300-5279-11eb-82b1-bccb594c254d.png)

Here's after converting to DevExpress:

![image](https://user-images.githubusercontent.com/2712328/104106239-fc290800-5279-11eb-9804-276f03e4f6c0.png)

It incorrectly sets the level of the footer to 0, it can be fixed in the designer by just changing the level to 1, but it would be nice to have it fixed in the converter.

![image](https://user-images.githubusercontent.com/2712328/104106245-064b0680-527a-11eb-881a-ba009e382d9c.png)

Here's a self-contained repro: [Simple.zip](https://github.com/DevExpress/Reporting.Import/files/5791627/Simple.zip)

**Comment by k0st1x** [comment]
please, repost this issue as a ticket in out [support center](https://supportcenter.devexpress.com/ticket/list), so we will fix it as a bug.
