### ISSUE TITLE
SSRS: KeepTogether with multiple columns not working correctly

### ISSUE THREAD

**Issue by markgould** [DevExpress/Reporting.Import#7]
SSRS Designer:
![image](https://user-images.githubusercontent.com/2712328/104106766-38119c80-527d-11eb-9cdc-f4ab73adc4fc.png)

SSRS Preview:
![image](https://user-images.githubusercontent.com/2712328/104106755-262ff980-527d-11eb-92dc-b7bd818e2d21.png)

DevExpress Designer:
![image](https://user-images.githubusercontent.com/2712328/104106772-41026e00-527d-11eb-81a6-9205f335f82d.png)

DevExpress Preview:
![image](https://user-images.githubusercontent.com/2712328/104106786-68593b00-527d-11eb-8266-a919b005abeb.png)

I've attached the RDL file here. I'll look to see if I can figure it out once I can fully understand how the tablix converter works.

[Balance Due Listing.zip](https://github.com/DevExpress/Reporting.Import/files/5791668/Balance.Due.Listing.zip)

**Comment by k0st1x** [comment]
please, repost this issue as a ticket in out [support center](https://supportcenter.devexpress.com/ticket/list), so we will fix it as a bug.
